name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build the thesis
        run: latexmk thesis && latexmk abstract-cz && latexmk abstract-en
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Thesis
          path: |
            *.pdf

  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout verifier
        uses: actions/checkout@v2
        with:
          repository: mff-cuni-cz/cuni-thesis-validator
          ref: ba1d9e7be0b70782bf19643eb9a7627ec046dfb7
      - name: Build verifier Docker image
        run: docker build -t thesis-validator .
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Thesis
      - name: Run verifier
        run: >
          docker run --rm -i -v $PWD:/thesis thesis-validator verify
          /thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0"'
